### PR TITLE
Reshape the whole API to improve dev experience

### PR DESCRIPTION
**Pull request by JOTSR**
Separated from the previous PR due to drastic API changes (imperative to OOP and promises)

# Motivation
Previous API follow C imperative paradigm and so force for manipulate pointer in the js side to manage windows. This new API approach take advantage of js class to hide pointer complexity like it was made in the Go API.

# Changes
- Fix TODO webui_wait
- Use enum from WebUi.Browser
- Export WebUi class to encapse previous API
- Add more examples
- Update doc
- Add live demo (examples can be run remotely by deno run -A --unstable example_url)

# TODO
- Update module version specifier in doc and examples for next tag
- Hash cached lib to auto clean old versions
- Improve async use of WebUi.script has ws response is awaited in the c lib
- Some simbols are not implemented and maybe not needed for the deno portage (to discuss)
- Update module version (~~maybe to 3.0.0 if it follow semver or is tracking webui c lib version ?~~)

As this lib solved many problems of the webview deno used in my project I'm interested in improving the module but there are no guidelines so I don't know on what and how continue.

### CODE REVIEW

**Comment by AlbertShown** [comment]
Thank you, @JOTSR, for this excellent and significant improvement 👍
My only comment is probably we should keep `webui` instead of `webUi`. What do you think?

_@hassandraga, please add @JOTSR to the team._

**Comment by JOTSR** [comment]
> Thank you, @JOTSR, for this excellent and significant improvement 👍 My only comment is probably we should keep `webui` instead of `webUi`. What do you think?
> 
> _@hassandraga, please add @JOTSR to the team._

To follow style conventions I used `WebUi`, `webui` is confusing I think, as JS style convention is to use camel case for variables and function and pascal case for class, types and interface maybe it is better to choose between `WebUI`, `WebUi`, `Webui`.

**Comment by AlbertShown** [comment]
I vote for `WebUI` !

**Comment by JOTSR** [comment]
Perfect, do I make a PR or an owner will make a commit ? After that I will work on the deno doc section of site.

**Comment by AlbertShown** [comment]
You can do a PR for now, but @hassandraga should invite you if you didn't receive an invitation yet, so you can commit directly to the repos.

**Pull request merged**
