### PR TITLE
upgrade to webui 2.4.0

### PR DESCRIPTION
**Pull request by AlbertShown**

### CODE REVIEW

**Review by fibodevy — APPROVED** [review]

**Comment by AlbertShown** [comment]
Thank you, you can merge it 👍

**Comment by fibodevy** [comment]
@AlbertShown Why are you no longer in the WebUI team? You left yourself?

**Comment by AlbertShown** [comment]
This is a professional account... my manager requested that I work and contribute to webui as we use it in some of our commercial diagnostic quick-run tools. After we released the software, I was not allowed to work on webui anymore... This deno minor contribution is my first personal free time contribution. however, it won't be the last one. we all like to contribute and learn new things, all can be added to the resume anyway 🤷‍♂️

**Comment by fibodevy** [comment]
Oh okay 🙂

**Pull request merged**
