### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by jeff-hykin**

### CODE REVIEW

**Review by fibodevy — CHANGES_REQUESTED** [review]
Binaries are not allowed

**Comment by jeff-hykin** [comment]
Sorry this was a mistake on my end, this PR was only supposed to change the readme. I'll get it fixed

**Comment by jeff-hykin** [comment]
Alright @fibodevy this is what I meant the PR to be

**Review by fibodevy — APPROVED** [review]
Thank you

**Pull request merged**
